### ISSUE TITLE
Can't finish pub get after adding angular_test

### ISSUE THREAD

**Issue by sturmf** [dart-lang/angular_test#33]
Hi,

so far I used package:angular2/src/modules/testing/lib/testing.dart for testing but it seems it broke with the latest angular2 updates. Anyways this seem to be the new kid on the block and I tried to port to it. Unfortunately I am already stuck at loading the dependencies. After I add angular_test to the pubspec.yaml  the following pub get will run forever.

Here my pubspec.yaml file for reference:

```
name: frontend
version: 0.0.1
description: Regatta frontend
author:
homepage: https://regatta.atlassian.net
documentation:

environment:
  sdk: '>=1.13.0 <2.0.0'

dependencies:
  angular2: any
  angular2_components: any
  browser: any
  dart_to_js_script_rewriter: any
  dson: any
  greencat: any
  http: any
  stream_transformers: any
  sass_transformer: any
  reflectable: any

dev_dependencies:
  dart_style: any
  test: any
  pageloader: any
  quiver: any
  mockito: any
  angular_test:
    git: git@github.com:dart-lang/angular_test.git

transformers:
  - angular2/transform/codegen:
      platform_directives:
        - package:angular2/common.dart#COMMON_DIRECTIVES
      platform_pipes:
        - 'package:angular2/common.dart#COMMON_PIPES'
      entry_points: web/main.dart
      resolved_identifiers:
        BrowserClient: 'package:http/browser_client.dart'
        Client: 'package:http/http.dart'
  - angular2/transform/reflection_remover:
      $include:
        - test/**_test.dart
        - web/main.dart
  - reflectable:
      entry_points:
        - web/main.dart
      formatted: true
  - test/pub_serve:
      $include: test/**_test.dart
  - dart_to_js_script_rewriter
  - sass_transformer

```
Running pub get -v prints tons of output like this:

SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select source_map_stack_trace 1.1.3 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | tuple 1.0.1 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select tuple 1.0.1 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | quiver_hashcode 1.0.0 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select quiver_hashcode 1.0.0 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | typed_data 1.1.3 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select typed_data 1.1.3 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | unittest 0.11.7 from hosted is locked but does not match >=0.10.0 <0.10.1
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | version 0.12.4+1 of unittest doesn't match >=0.10.0 <0.10.1:
    | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |   dson 0.1.0 from hosted -> unittest >=0.10.0 <0.10.1 from hosted (unittest)
SLVR: |
